// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // BERUBAH: Android app ini (com.mirailabs.quran_report) sekarang
  // resmi nunjuk ke project quran-reportweb (project yang beneran
  // punya Firestore Database) -- diambil dari google-services.json
  // project quran-reportweb.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs1M0fxMZLh0hL2sLXsSicgHzohHbe344',
    appId: '1:110737865436:android:e4264999f8f45e1bdb9219',
    messagingSenderId: '110737865436',
    projectId: 'quran-reportweb',
    storageBucket: 'quran-reportweb.firebasestorage.app',
  );

  // BERUBAH: sama kayak android -- ini akar penyebab web-app timeout
  // pas Backup/Deploy.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0uR2q8_nfldRT6_yYnqR1m-ZUdqCFbw',
    appId: '1:110737865436:web:ca09856908c942ffdb9219',
    messagingSenderId: '110737865436',
    projectId: 'quran-reportweb',
    authDomain: 'quran-reportweb.firebaseapp.com',
    storageBucket: 'quran-reportweb.firebasestorage.app',
  );

  // <-- CATATAN: macos/ios/windows di bawah ini BELUM diupdate --
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArAfIbTJnvpb5W0sQBxS_GyqypHEKIBE4',
    appId: '1:665962415231:ios:3d4420668a72459272ab4a',
    messagingSenderId: '665962415231',
    projectId: 'quran-report',
    storageBucket: 'quran-report.firebasestorage.app',
    iosBundleId: 'com.mirailabs.quranReport',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArAfIbTJnvpb5W0sQBxS_GyqypHEKIBE4',
    appId: '1:665962415231:ios:3d4420668a72459272ab4a',
    messagingSenderId: '665962415231',
    projectId: 'quran-report',
    storageBucket: 'quran-report.firebasestorage.app',
    iosBundleId: 'com.mirailabs.quranReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF6B7XiuLVgdN9sAXseD2V6VGUe1Ep1Rw',
    appId: '1:665962415231:web:09e8ca222834bcd872ab4a',
    messagingSenderId: '665962415231',
    projectId: 'quran-report',
    authDomain: 'quran-report.firebaseapp.com',
    storageBucket: 'quran-report.firebasestorage.app',
  );
}
