// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBConv1P4QyHxEYNij4AkgYmA7kI63ma7g',
    appId: '1:665962415231:android:7096f42eea903da972ab4a',
    messagingSenderId: '665962415231',
    projectId: 'quran-report',
    storageBucket: 'quran-report.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF6B7XiuLVgdN9sAXseD2V6VGUe1Ep1Rw',
    appId: '1:665962415231:web:2d25b7857107294472ab4a',
    messagingSenderId: '665962415231',
    projectId: 'quran-report',
    authDomain: 'quran-report.firebaseapp.com',
    storageBucket: 'quran-report.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArAfIbTJnvpb5W0sQBxS_GyqypHEKIBE4',
    appId: '1:665962415231:ios:3d4420668a72459272ab4a',
    messagingSenderId: '665962415231',
    projectId: 'quran-report',
    storageBucket: 'quran-report.firebasestorage.app',
    iosBundleId: 'com.mirailabs.quranReport',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArAfIbTJnvpb5W0sQBxS_GyqypHEKIBE4',
    appId: '1:665962415231:ios:3d4420668a72459272ab4a',
    messagingSenderId: '665962415231',
    projectId: 'quran-report',
    storageBucket: 'quran-report.firebasestorage.app',
    iosBundleId: 'com.mirailabs.quranReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF6B7XiuLVgdN9sAXseD2V6VGUe1Ep1Rw',
    appId: '1:665962415231:web:09e8ca222834bcd872ab4a',
    messagingSenderId: '665962415231',
    projectId: 'quran-report',
    authDomain: 'quran-report.firebaseapp.com',
    storageBucket: 'quran-report.firebasestorage.app',
  );
}
